### ISSUE TITLE
Update the npm package release to make --next releases

### ISSUE THREAD

**Issue by aimensahnoun** [RequestNetwork/web-components#178]
### Problem:

The current Github action only makes a release if we specifically change the package version, and it only makes stable releases.

We would like to update it to make `--next` releases as well, this would help when we need to use the packages but do not want to make a stable release yet.

**Comment by aimensahnoun** [comment]
Previous PR had a mistake, fix was added to this PR: https://github.com/RequestNetwork/web-components/pull/180

**Comment by MantisClone** [comment]
Nice work @aimensahnoun!
