### ISSUE TITLE
Make `currencies` and `payment chain` input parameter _override_ the default currency and payment chains list instead of append

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/web-components#209]
# Problem

In the Invoice Dashboard and Create React Form, the `currencies` input parameter appends to the default currency list. This means that there's no way for an App Builder to _remove_ a currency from the default currency list.

# Solution

Add another parameter: override or append

**Comment by Fpinto29** [comment]
Added payment chains to the scope of this task
