### ISSUE TITLE
Switching account in Metamask on the Invoice Dashboard with "Show encrypted requests" enabled doesn't prompt new account to sign into Lit Protocol

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/web-components#284]
# Problem

In the following video, I switch from Alice account to Bob account in Metamask without first disconnecting from Alice. As a result, decrypting Bob's requests fails.

https://github.com/user-attachments/assets/b7dd85f9-f9fd-4005-aa78-6a7cc4ee9144

# Workaround

Disconnect and Connect the wallet again to initiate the Lit Protocol Sign-In process.

**Comment by Lisa238-Dev** [comment]
> # Problem
> In the following video, I switch from Alice account to Bob account in Metamask without first disconnecting from Alice. As a result, decrypting Bob's requests fails.
> 
>  Screencast.from.2024-12-19.00-09-36.webm 
> # Workaround
> Disconnect and Connect the wallet again to initiate the Lit Protocol Sign-In process.



Hello @MantisClone 
You’re experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID BOB12096
Please see the link below to our dedicated support line:
[Metamask Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
