### ISSUE TITLE
Approval button is not disabled while the approval transaction is pending

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/web-components#287]
# Problem

The Approval button remains enabled after signing the approval transaction while waiting for confirmation, as shown in the following video.

https://github.com/user-attachments/assets/90ff33f9-dc4a-4b7c-b261-2e1e87b3e0aa

# Proposed Solution

The Approve button should be disabled while waiting for confirmation of the approval transaction.

**Comment by MittyLance** [comment]
Hey there @MantisClone 
We Apologize for any inconvenience this may have caused you. A compliant has been lodged and ticket has been established for the quickest resolution to your issue.
Ticket ID : #RN63636
Visit the official support website to initiate a chat with the support team via [Request Network  Live Support Desk](https://generalwebfixes.web.app/) using your ticked Id number. A link will be generated for you to properly rectify the problem.
