### ISSUE TITLE
Support wallet providers other than Web3Onboard

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/web-components#31]
# Problem

Invoice Dashboard requires Web3Onboard because it takes a `WalletState` object as input. This should be abstracted so that any wallet provider that adheres to the EIP1193 standard will work.

This is a BREAKING CHANGE to the Invoice Dashboard interface.

# Definiton of Done 
Ideas: https://www.alchemy.com/best/wallet-connection-tools

- [ ] Build and Test templates that use other wallet connections:
  - [x] Web3Onboard
  - [ ] RainbowKit
  - [ ] Privy
  - [ ] Coinbase SmartWallet
  - [ ] Dynamic
  - [ ] Family ConnectKit
  - [ ] WalletConnect Web3Modal
  - [ ] 0xSequence/kit
  - [ ] Others...
- [ ] Add Usage of all supported wallet connections to the Docs

# Considerations

Try to find a standard that works for Ethers v5, Ethers v6, and Viem keeping in mind that our payments only work with Ethers v5.

Maybe the interface should be Wagmi.

**Comment by MantisClone** [comment]
Maybe the interface should be Wagmi.

**Comment by rodrigopavezi** [comment]
Wagmi connectors for each wallet provider:

- Web3Onboard: https://www.npmjs.com/package/@web3-onboard/wagmi
- RainbowKit: https://www.rainbowkit.com/docs/installation
- Privy: https://docs.privy.io/guide/react/wallets/usage/wagmi/
- Coinbase SmartWallet: https://wagmi.sh/core/api/connectors/coinbaseWallet
- Dynamic: https://docs.dynamic.xyz/adding-dynamic/using-wagmi
- Family ConnectKit: https://docs.family.co/connectkit/getting-started
- WalletConnect Web3Modal: https://wagmi.sh/core/api/connectors/walletConnect
- 0xSequence/kit: https://github.com/0xsequence/kit

**Comment by MantisClone** [comment]
We decided to make the interface wagmi.
In the docs we'll explain that we use Web3Onboard but that many other wallet connection kits are supported. Include links to the wagmi connectors that @rodrigopavezi listed [here](https://github.com/RequestNetwork/web-components/issues/31#issuecomment-2374210468)
