### ISSUE TITLE
On the Invoice Dashboard, the status column doesn't update to "Paid" after making a payment. It requires a page refresh.

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/web-components#40]
# Problem

On the Invoice Dashboard, the status column doesn't automatically update to "Paid" after making a payment. It requires a page refresh.

# Proposed Solution

After a payment, the table should poll the Invoice `request.refresh()` until the `balance` is updated.

**Comment by sstefdev** [comment]
I could not reproduce this. Can someone share a video of this happening? Curious when does it happen
