### ISSUE TITLE
Add React shims to hide useRef to make Web Components built with Svelte easier to use

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/web-components#67]
Follow-up to https://github.com/RequestNetwork/web-components/issues/34

# Problem

Svelte's Object parser always calls `JSON.stringify` and `JSON.parse` which doesn't work for complex objects that have Functions.

![Image](https://github.com/RequestNetwork/web-components/assets/2530913/e628f5d2-a376-4e5f-9c89-5c1fb77ba1fa)

# Proposed Solution

Create React Shims that handle the useRef to simplify the Dev EX for integrating the components.

- [x] payment-widget
- [ ] invoice-dashboard
- [ ] create-request-form

# Alternatives

* Reimplement Web Components using https://lit.dev/ which may or may not have the same Object parsing limitation as Web Components written in Svelte.

**Comment by aimensahnoun** [comment]
This was achieved in https://github.com/RequestNetwork/web-components/tree/main/packages/payment-widget/src/lib/react.

**Comment by MantisClone** [comment]
Re-open so we can apply the same fixes to the invoice-dashbaord and create-request-form
