### ISSUE TITLE
Request status column should show "Pending" if request `state` is `pending`

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/web-components#97]
# Problem

Pending requests show in the dashboard as "Created".
![Image](https://github.com/user-attachments/assets/add97a11-528f-4a4b-831c-9f27f41e93d6)
https://github.com/RequestNetwork/web-components/blob/f335da93759556b547eadc285d71ad052b6b4f7d/packages/invoice-dashboard/src/lib/view-requests.svelte#L244-L252

# Proposed Solution

Logic should check `request.state` after checking the balance. Support all possible states including Pending, Created, Accepted, and Canceled.
https://github.com/RequestNetwork/requestNetwork/blob/0320158c77b69f3255106df8ab0b649faac21f04/packages/types/src/request-logic-types.ts#L308-L315
```ts
/** States of a request */
export enum STATE {
  // use for upper layer (trick to avoid headache with retyping request in upper layer)
  PENDING = 'pending',
  CREATED = 'created',
  ACCEPTED = 'accepted',
  CANCELED = 'canceled',
}
```

# Considerations

What status to show for partially paid requests?

**Comment by Fpinto29** [comment]
Approved, seems better than accepted
